default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: neighborly
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  schema_search_path: myapp,sharedapp,public
  min_messages: error

development:
  <<: *default

test:
  <<: *default
  database: neighborly_test

production:
  <<: *default
  database: neighborly_production
  username: neighborly
  password: <%= ENV["NEIGHBORLY_DATABASE_PASSWORD"] %>
